package com.example.zorodemo.zorodemo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBDocument
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "damage")
public class Damage {
    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "damageid")
    private int damageid;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "movename")
    private String moveName;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "crewid")
    private String crewid;


    //@DynamoDBAutoGeneratedDefault(value = "99")
    @DynamoDBAttribute(attributeName = "damagePerMove")
    private int damagePerMove;

    public Damage(String moveName, String crewid, int damagePerMove) {
        this.moveName = moveName;
        this.crewid = crewid;
        this.damagePerMove = damagePerMove;
    }
}
