package com.example.zorodemo.zorodemo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import com.example.zorodemo.zorodemo.util.DamageTypeConverter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "strawhats")

public class Pirates {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String crewid;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "firstname")
    private String firstname;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "lastname")
    private String lastname;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "weapontype")
    private String weaponType;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "specialAttack")
    private String specialAttack;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "devilFruit")
    private boolean devilFruit;

    //@DynamoDBAutoGeneratedDefault(value = "-1")
    @DynamoDBAttribute(attributeName = "devilFruitName")
    private String devilFruitName;

    @DynamoDBAttribute(attributeName = "damage")
    @DynamoDBTypeConverted(converter = DamageTypeConverter.class)
    private Damage damage;

}
