package com.example.zorodemo.zorodemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBDocument
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "damage")
public class Damage {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int damageid;

    @DynamoDBAttribute
    private String moveName;

    @DynamoDBAttribute
    public String crewid;

    @DynamoDBAttribute
    private int damagePerMove;
}
