package com.example.zorodemo.zorodemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "damage")
public class Damage {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int moveid;

    @DynamoDBAttribute
    private String moveName;

    @DynamoDBAttribute
    private String damagePerMove;
}
